name: Normalize DOCX to Markdown

on:
  push:
    paths:
      - "**/*.docx"

permissions:
  contents: write

jobs:
  normalize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc and file
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc file

      - name: Convert binary DOCX → Markdown (overwrite with .docx extension)
        run: |
          for file in *.docx; do
            [ -e "$file" ] || continue

            # Detect if it's a real DOCX (binary/zip)
            if file "$file" | grep -q "Microsoft Word"; then
              echo "Converting $file → normalized Markdown (keeping .docx extension)..."
              pandoc "$file" -t markdown -o "$file" --extract-media="${file%.docx}.media"
            else
              echo "Skipping $file (already normalized Markdown)"
            fi
          done

      - name: Commit normalized files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add *.docx */*.media/* || true

          if ! git diff --cached --quiet; then
            git commit -m "Normalize DOCX to Markdown (keeping .docx name)"
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          else
            echo "No changes to commit."
          fi

