name: Sync DOCX and Markdown

on:
  push:
    paths:
      - "**.docx"

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc unzip

      - name: Convert DOCX to Markdown + Extract Images
        run: |
          for f in $(find . -name "*.docx"); do
            mdfile=$"{f%.docx}.md"
            pandoc "$f" -o "$mdfile" --extract-media=media
          done

      - name: Commit generated Markdown + images
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add *.md media/*
          git diff --cached --quiet || git commit -m "Auto-convert DOCX to MD + images"
          git push
